### ISSUE TITLE
Unknow type raster

### ISSUE THREAD

**Issue by ddegasperi** [jsor/doctrine-postgis#10]
Like geometry and geography there should be support for type raster (introduced with PostGIS 2.x)

I've got the following error message:

> [Doctrine\DBAL\DBALException]  
>   Unknown database type raster requested, Doctrine\DBAL\Platforms\PostgreSQL92Platform may not support it.

**Comment by jsor** [comment]
The [v1.1.0](https://github.com/jsor/doctrine-postgis/releases/tag/v1.1.0) release contains a raster DBAL type.

Note, that at the moment, this type is not fully suited to be used in entity mappings (there is no support for spatial indexes for this type for example). It just prevents "Unknown database type..." exceptions thrown during database inspections by the schema tool.

**Comment by jsor** [comment]
Closing for now, feel free to reopen if needed.
