### ISSUE TITLE
ST_AsEWKT in Doctrine Type when converting to PHP value

### ISSUE THREAD

**Issue by teohhanhui** [jsor/doctrine-postgis#11]
I'm a complete newbie in GIS, but I'm wondering...

What is the point of using `ST_AsEWKT` for converting to PHP value, when `ST_GeomFromText` is used when converting to SQL value?

Also, since the SRID is already configured as an option on the field, doesn't that mean it should not change in the first place?

**Comment by jsor** [comment]
Simply to return as much information as possible (including the SRID) without having to know the property mapping.

**Comment by teohhanhui** [comment]
But that means it's no longer valid WKT... Is that really worth it? At least it could be made configurable?

**Comment by jsor** [comment]
Why would you want to drop the SRID? Any decent WKT parser should at least be able to ignore the SRID. Whats the use case for having WKT instead of EWKT?

**Comment by teohhanhui** [comment]
I guess I'm just being pedantic, but it's good to have standard WKT strings.

**Comment by jsor** [comment]
I can't change it now as it would be a BC break for users relying on EWKT being returned.
The point is, you can convert EWKT to WKT, but you can't the other way around.

You can use a [WKT Parser](https://github.com/geo-io/wkt-parser) / [WKT Generator](https://github.com/geo-io/wkb-generator) to convert to pure WKT.
