### ISSUE TITLE
Weird parsing of boolean functions in DQL

### ISSUE THREAD

**Issue by teohhanhui** [jsor/doctrine-postgis#14]
The following DQL:

``` sql
SELECT b
FROM AppBundle\Entity\EntityB b
INNER JOIN AppBundle\Entity\EntityA a
    WITH ...
    AND ST_Contains(a.geom, b.geom)
WHERE
...
```

gives

> Error: Expected =, <, <=, <>, >, >=, !=, got 'WHERE'

The workaround is to change it to:

``` sql
ST_Contains(a.geom, b.geom) = true
```

Is this a DQL quirk, or something that we can fix?

**Comment by jsor** [comment]
As far as i understand it, DQL requires a comparision operator in conditional expressions. There are only a few hard-coded exceptions like BETWEEN, IN, LIKE expressions:

https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Query/Parser.php#L2568-L2596
