### ISSUE TITLE
SPATIAL index not created

### ISSUE THREAD

**Issue by FredoVelcro-zz** [jsor/doctrine-postgis#16]
I have this entity with a spatial index (polygons)

``` php
/**
 * @ORM\Entity()
 * @ORM\Table(name = "mytable",
 *      options={"spatial_indexes"={"polygons_idx"}},
 *      indexes={
 *          @ORM\Index(name="polygons_idx", columns={"polygons"})
 *      }
 * )
 */
class MyTable
{
    /**
     * @var int
     *
     * @ORM\Column(type = "integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy = "AUTO")
     */
    protected $id;

    /**
     * @var int
     *
     * @ORM\Column(name="polygons", type = "geometry")
     */
    protected $polygons;

    /* ... */

}
```

What Doctrine tries to create upon schema update : 

``` sql
CREATE TABLE mytable (id INT AUTO_INCREMENT NOT NULL, polygons GEOMETRY NOT NULL COMMENT '(DC2Type:geometry)', INDEX polygons_idx (polygons), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
```

I have this error 

`SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'polygons' used in key specification without a key length`

I think the problem is that **keyword SPATIAL is missing** in the index creation.
INDEX polygons_idx (polygons) should be INDEX SPATIAL polygons_idx (polygons) i think no ?

**Comment by jsor** [comment]
`ENGINE = InnoDB` tells me you're trying to use this lib with MySQL. As the name `doctrine-postgis`says, this library is for usage with PostGIS/PostgreSQL only ;)

**Comment by FredoVelcro-zz** [comment]
oh sorry ! ;)
You're right i use MySQL 5.7

**Comment by jsor** [comment]
No Problem 😄 
You could give [doctrine2-spatial](https://github.com/creof/doctrine2-spatial) a try which supports MySQL.

**Comment by FredoVelcro-zz** [comment]
yes i already use it but it doesn't support SPATIAL index creation (on schema update)
