### ISSUE TITLE
Zend Framework 2 + Unknown column type "geometry"

### ISSUE THREAD

**Issue by altamiro** [jsor/doctrine-postgis#2]
[Sun May 31 10:15:10.106812 2015] [:error] [pid 21830] [client 127.0.0.1:36340] PHP Fatal error:  Uncaught exception 'Doctrine\DBAL\DBALException' with message 'Unknown column type "geometry" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.' in /home/altamiro/Developments/Projects/bitbucket/siema/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:228\nStack trace:\n#0 /home/altamiro/Developments/Projects/bitbucket/siema/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php(172): Doctrine\DBAL\DBALException::unknownColumnType('geometry')\n#1 /home/altamiro/Developments/Projects/bitbucket/siema/vendor/doctrine/orm/lib in /home/altamiro/Developments/Projects/bitbucket/siema/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php on line 228, referer: http://localhost:86/

**Comment by altamiro** [comment]
$doctrineEntityManager = $e->getApplication()->getServiceManager()->get('Doctrine\ORM\EntityManager');
        $doctrineEntityManager->getEventManager()->addEventSubscriber(new ORMSchemaEventSubscriber());

```
    $doctrineConnection = $e->getApplication()->getServiceManager()->get('doctrine.connection.orm_default');
    $doctrineConnection->getEventManager()->addEventSubscriber(new DBALSchemaEventSubscriber());

    $configuration = new DoctrineConfiguration();
    JsorConfigurator::configure($configuration);
```

**Comment by jsor** [comment]
I'm not familiar with how to configure Doctrine Event Subscribers correctly in ZF2. But i suspect, the subcriber isn't registered correctly (or maybe early enough). Btw, you only need to register either ORMSchemaEventSubscriber **or** DBALSchemaEventSubscriber, not both.

As far as i can tell, there should be something like this in your configuration:

``` php
'doctrine' => array(
    'eventmanager' => array(
        'orm_default' => array(
            'subscribers' => array(
                'Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber'
            ),
        ),
    ),
),
```

**Comment by jsor** [comment]
Closing for now, feel free to reopen if needed.

**Comment by angelocavallet** [comment]
Thank you so much @jsor !!!
I'm looking for this tip like a crazy haahahhaa
And thanks for this project :smile:
