### ISSUE TITLE
Symfony PostGIS - db reverse engineering

### ISSUE THREAD

**Issue by mysiar** [jsor/doctrine-postgis#23]
Hi
I hit problem. Not sure if this could be treated as issue but maybe you can help me out.
http://stackoverflow.com/questions/41237585/symfony-postgis-db-reverse-engineering

Cheers

**Comment by jsor** [comment]
Hard to say without, but i suspect there is somthing wrong with the Postgres/PostGIS setup or the DB credentials have no access to the schema.

**Comment by mysiar** [comment]
Ok. I will create brand new postgis database with simple table and will try again

**Comment by mysiar** [comment]
problem was **search_path**
as soon I set it up everything works as expected
