### ISSUE TITLE
Disabling posts extension with other database

### ISSUE THREAD

**Issue by drewprod** [jsor/doctrine-postgis#24]
Hi,

I need to change my db only for test to sqlite.
After reading your code, you never check if it's PostgreSQLPlatform or not.
Do you know if i can disabled your extension and annotation just for test environnement ?

Regards

**Comment by jsor** [comment]
This depends on your setup. The easiest way would be to have separate test / production configs or bootstrap scripts where you register the subscriber only for production.

**Comment by jsor** [comment]
Closing due to lack of feedback. Feel free to reopen if you have further questions.
