### ISSUE TITLE
Deprecation warnings for ST_Distance_Sphere

### ISSUE THREAD

**Issue by JunkMyFunk** [jsor/doctrine-postgis#32]
Running doctrine-postgis 1.4.1 I am seeing deprecation warnings from PostGIS in our logs:

```
SQL function "st_distance_sphere" during startup
WARNING:  ST_Distance_Sphere signature was deprecated in 2.2.0. Please use ST_DistanceSphere
CONTEXT:  PL/pgSQL function _postgis_deprecate(text,text,text) line 14 at RAISE
```

We are using Symfony and the DQL function is mapped in the config like this: 

```
ST_Distance_Sphere:     Jsor\Doctrine\PostGIS\Functions\ST_Distance_Sphere
```

The DQL producing the warning looks something like this

```php
->addSelect("ST_Distance_Sphere(pl.geom, ST_Geomfromtext('POINT($long $lat)', 4326)) AS distance")
```

**Comment by jsor** [comment]
Thanks for the report. I've just released v1.5.0 with the new functions. See https://github.com/jsor/doctrine-postgis/releases/tag/v1.5.0

**Comment by jsor** [comment]
@JunkMyFunk Did that solve your issues?

**Comment by jsor** [comment]
Closing due to lack of feedback.

**Comment by JunkMyFunk** [comment]
sorry just had a chance to test this. I've updated my config and DQL to use the new `ST_DistanceSphere` functions and the deprecation warnings are gone, tests are passing so looks good to me. Thanks very much @jsor

**Comment by jsor** [comment]
Awesome, thanks for the feedback! 👍
