### ISSUE TITLE
I use symfnoy3.4 ,  execute some commands in console,an same error occurred," ...syntax to use near 'current_schemas(false)) )..." 

### ISSUE THREAD

**Issue by englenshan** [jsor/doctrine-postgis#37]
An error occurred when I performed some database entity updates or created entities in the console:

_SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corres  
  ponds to your MySQL server version for the right syntax to use near 'current_schemas(false)) )                              
                  ORDER BY i.relname' at line 8_  

I checked the code and found the location of the error code.
location:`E:\xampps\htdocs\myProj\vendor\jsor\doctrine-postgis\src\Schema\SchemaManager.php`,52 line.
like this 
`` public function listSpatialIndexes($table)
    {
        if (false !== strpos($table, '.')) {
            list(, $table) = explode('.', $table);
        }
        #$sql ,This is the code where the error occurred.
        $sql = "SELECT distinct i.relname, d.indkey, pg_get_indexdef(d.indexrelid) AS inddef, t.oid
                FROM pg_class t
                INNER JOIN pg_index d ON t.oid = d.indrelid
                INNER JOIN pg_class i ON d.indexrelid = i.oid
                WHERE i.relkind = 'i'
                AND d.indisprimary = 'f'
                AND t.relname = ?
                AND i.relnamespace IN (SELECT oid FROM pg_namespace WHERE nspname = ANY (current_schemas(false)) )
                ORDER BY i.relname";

        $tableIndexes = $this->connection->fetchAll(
            $sql,
            array(
                $this->trimQuotes($table)
            )
        );

        $indexes = array();
        foreach ($tableIndexes as $row) {
            if (!preg_match('/using\s+gist/i', $row['inddef'])) {
                continue;
            }

            $sql = "SELECT a.attname, t.typname
                    FROM pg_attribute a, pg_type t
                    WHERE a.attrelid = {$row['oid']}
                    AND a.attnum IN (" . implode(',', explode(' ', $row['indkey'])) . ')
                    AND a.atttypid = t.oid';

            $stmt = $this->connection->executeQuery($sql);
            $indexColumns = $stmt->fetchAll();

            foreach ($indexColumns as $indexRow) {
                if ('geometry' !== $indexRow['typname'] &&
                    'geography' !== $indexRow['typname']) {
                    continue;
                }

                if (!isset($indexes[$row['relname']])) {
                    $indexes[$row['relname']] = array();
                }

                $indexes[$row['relname']][] = trim($indexRow['attname']);
            }
        }

        return $indexes;
    }

**Comment by jsor** [comment]
Just to make sure: this library is intended to be used with **PostGIS** for **PostgreSQL**. It does **not** work with MySQL.

**Comment by englenshan** [comment]
Obviously, the database I am using is MYSQL.
I tried to query and modify, including the operation of calculating some distances.
I found no errors in Mysql. 
If possible, it is perfectly compatible with Mysql, I believe this is the library must be better.
Then I also found another library, on gitHub:
      https://github.com/creof/doctrine2-spatial
You may get some useful information from it.
I will try and solve this problem in other ways.
BTW,forgive my Chinglish, I am too poorly expressed.
thanks again.
