### ISSUE TITLE
Unknow type geometry

### ISSUE THREAD

**Issue by maxthev** [jsor/doctrine-postgis#4]
I guess this is not the same problem, 

now i have :

```
[Doctrine\DBAL\DBALException]
Unknown database type geometry requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.
```

looks like "geography" type works well but "geometry" does not ...

**Comment by jsor** [comment]
I've answered here: https://github.com/jsor/doctrine-postgis/issues/3#issuecomment-124130962
