### ISSUE TITLE
Unknown database type _text requested

### ISSUE THREAD

**Issue by SDenman** [jsor/doctrine-postgis#44]
Hi there,
Wondered if anyone has come up against this:
CREATE EXTENSION
In AbstractPlatform.php line 434:
Unknown database type **_text** requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support it.

I'm running Symfony 4 as part of an API-Platform installation on Docker. But I wanted to add PostGIS so am trying the https://hub.docker.com/r/mdillon/postgis image instead of the vanilla postgres included with API-Platform.

I followed the installation and setup instructions included in your documentation and it seems to load ok until it comes across _text database type as shown in the log above.

I realise it's probably a bit too convoluted to try and reproduce, but any guesses as to what might be happening and how to work around it would be great.

OK - Sorry - fixed it already by mapping the type under the Doctrine - dbal - declaration in doctrine.yaml:
mapping_types:
         _text: string

**Comment by paolostefan** [comment]
@SDenman same fix for me too: maybe it should be added to the install docs.

**Comment by Nek-** [comment]
It has been added to the doc but it's actually wrong. `_text` seems to represent an array of strings (and to be an alias (??) of `text[]`).

Sources:
- First, you need to know there's nothing about [in the documentation](https://www.postgresql.org/docs/13/arrays.html)
- But it looks that as soon as you relate [to array you are in trouble with postgres](https://github.com/martin-georgiev/postgresql-for-doctrine/issues/73)
- [Trying to make a `text[]` column that results in `_text`](https://github.com/hasura/graphql-engine/issues/1170)
- [Same problem](https://github.com/dbeaver/dbeaver/issues/6176)

The best part of all of this is that it's not even related to this library but postgis uses arrays.
