### ISSUE TITLE
how to use this extension with the create extension postgis being done in doctrine migrate

### ISSUE THREAD

**Issue by allan-simon** [jsor/doctrine-postgis#45]
it seems that it's not possible (or at least I haven't found a way) to activate this extension while having the 
```sql
create extension postgis
```
being done in one of the late migration

 i.e you can't have a project that in 1.0 does not use postgis and have already some doctrine migration existing, and that in 2.0 you start using it , and you want to introduce this library + having a doctrine migration that will do `create extension postgis`,  otherwise when you will try to re-run the migration from scratch (for example when creating a test environment)

as when initializing doctrine, it will trigger this error 

```
In AbstractPostgreSQLDriver.php line 79:
                                                                                                            
  An exception occurred while executing 'SELECT PostGIS_Lib_Version()':                                     
                                                                                                            
  SQLSTATE[42883]: Undefined function: 7 ERROR:  function postgis_lib_version() does not exist              
  LINE 1: SELECT PostGIS_Lib_Version()                                                                      
                 ^                                                                                          
  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.  
                                                                                                           
```

which is done here: 

```
./vendor/jsor/doctrine-postgis/src/Schema/SchemaManager.php:    public function isPostGis2()
```

would you accept a patch that catch this error , throw a warning instead and return false ?

**Comment by jcrombez** [comment]
@allan-simon I'm in the same situation, did you find a workaround ?

**Comment by allan-simon** [comment]
no, as the problem was only on my local dev environment, I actually switch to a docker image of postgis, so with the extension already activated. 

a workaround,  could be to deactivate this feature,  make a manual doctrine migration where you activate this extension  , release, and then reactivate and re-release :thinking:

**Comment by jsor** [comment]
I don't think it is a good idea to configure the database via migrations. As you already said, my suggestions would be also, to [enable the extension on container startup](https://github.com/docker-library/docs/tree/8a11a9db9bd2836e8091823ed13c6305326cb483/postgres#additional-extensions) or simply switch to a Docker image with the extension already enabled, e.g. [postgis/postgis](https://registry.hub.docker.com/r/postgis/postgis).
