### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by metalfm** [jsor/doctrine-postgis#48]
Hello! 

Are you planning to implement php 8 support?

**Comment by adapik** [comment]
any news?

**Comment by jsor** [comment]
The release [v1.8.0](https://github.com/jsor/doctrine-postgis/releases/tag/v1.8.0) now allows installation on PHP 8.

**Note:** While it is possible to install this library on PHP 8, it is **not** officially support right now. Use with care and at your own risk.
