### ISSUE TITLE
Upgrading the test suite to Postgis 3.1

### ISSUE THREAD

**Issue by Nek-** [jsor/doctrine-postgis#52]
Hello. I worked on making the testsuite work for PHP 8.0 and I was testing stuff with postgis 3.1.

There's a lot of work to test postgis 1.5, 2.0, 2.1, and 2.2. But it's even harder now because many many many outputs from postgis have changed. Especially precision in calculations (leading to barely all numbers wrong in expected results).

To support PHP 7.1 as well as 8.0 in the test suite, I currently have no other solution than using the PHPUnit Bridge of Symfony, but it seems working nicely.

I post this because I can push my code as a PR but **I want to know if you're ok to drop testsuite for old versions of postgis**. If so, I'll send a pull request. (the work I did so far is already huge, so I'm not going to make old versions of postgis work with it)

**Comment by jsor** [comment]
Fixed and released in [v2.0.0](https://github.com/jsor/doctrine-postgis/releases/tag/v2.0.0).
