### ISSUE TITLE
Problem using with dama/doctrine-test-bundle

### ISSUE THREAD

**Issue by Kolbasyatin** [jsor/doctrine-postgis#54]
There is problem after install [dama/doctrine-test-bundle](https://symfony.com/doc/current/testing.html#resetting-the-database-automatically-before-each-test).

LogicException : It looks like you have registered the Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber to more than one connection. Please register one instance per connection.

How can I resolve this problem ?

**Comment by jsor** [comment]
I've just released v2.1.0. This should be fixed now.

**Comment by hharrari-labs** [comment]
Hello do you have a solution for those who cannot be in php 8 ?
