### ISSUE TITLE
It looks like you have registered the Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber to more than one connection.

### ISSUE THREAD

**Issue by tasselchof** [jsor/doctrine-postgis#56]
Hello!

I saw issue #17 and I have a question: is the reason to have it the same? I am getting this when I try to switch a connection. I have two connections to the databases (almost like mater-slave, but second connection is manually done to statistics database.

**Comment by jsor** [comment]
This has been fixed with the [2.1.0](https://github.com/jsor/doctrine-postgis/releases/tag/v2.1.0) release.
