### ISSUE TITLE
 The geometry_type of a spatial column cannot be changed

### ISSUE THREAD

**Issue by maxthev** [jsor/doctrine-postgis#6]
Hey, it's me again !

When i use :

```
php app/console doctrine:schema:update --dump-sql
```

i have this : 

```
 [RuntimeException]
  The geometry_type of a spatial column cannot be changed (Requested changing type from "POINT" to "GEOMETRY" for column "coordinates" in table "company")
```

But i didn't ask to change the type...
My entity is exactly the same as doctrine created with mapping:import 

```
/**
     * @var geography
     *
     * @ORM\Column(name="coordinates", type="geography", nullable=true)
     */
    private $coordinates;
```

I didn't change anything, so i don't understand why it does not work.

thanks

**Comment by maxthev** [comment]
I changed my Entity to this : 

```
/**
     * @var geography
     *
     * @ORM\Column(name="coordinates", type="geography", nullable=true, options={"geometry_type"="POINT", "srid"=4326})
     */
    private $coordinates;
```

And now I can use schema:update without any error.

**Comment by jsor** [comment]
Yes, that is the correct solution. If you do not define a geometry_type, the generic type "geometry" is used, so in this case you would change a Point type to a Geometry type which produces the exception.

**Comment by maxthev** [comment]
i saw this =D Thanks

**Comment by jmechevarria** [comment]
hi guys, I know it's been a while but, I am having exactly the same problem with a symony2 entity field:

```
    /**
     * @var geometry
     *
     * @ORM\Column(name="geom", type="geometry", options={"geometry_type"="MULTIPOLYGON", "srid"=3795}, nullable=true)
     */
    private $geom;
```

 although in my case the type is geometry, not geography like maxthev's, dunno if it is relevant. 
As you can see, I followed maxthev's solution but it still throws back error

```
[RuntimeException]                                                                                                   
  The geometry_type of a spatial column cannot be changed (Requested changing type from "MULTIPOLYGON" to "GEOMETRY"   
  for column "geom" in table "area_intrusion_marina")
```

when I try to `"doctrine:schema:update" "--force"`.

the type of the field in the table as I see it in pgAdmin is **geometry(MultiPolygon, 3795)**

I'm using Jsor library with doctrine to map the spatial types, if you need any other data, just let me know

could you please help me?

**Comment by jsor** [comment]
Did you actually changed the column definition? Or does this error happens despite you haven't changed anything? Also, what version of Prostgres and PostGIS are you using?

**Comment by jmechevarria** [comment]
I'm really sorry! already noticed the problem (someone at [gis](https://gis.stackexchange.com) helped me notice it).

**Problem**: I had reversed-engineered the DB with `doctrine:mapping:import` and `doctrine:mapping:convert`. As a remainder of the first command, file `TableName.orm.xml` was created and I never thought of deleting it, so basically, every time I ran `doctrine:schema:update --force` it was looking in the xml for the metadata config, not in the actual php entity class, so it didn't matter what interrogation technique I used on 
```
    /**
     * @var geometry
     *
     * @ORM\Column(name="geom", type="geometry", options={"geometry_type"="MULTIPOLYGON", "srid"=3795}, nullable=true)
     */
    private $geom;
```
in `TableName.php`, it was not going to talk.

Sorry again and thanx for the reply!

**Comment by jsor** [comment]
Glad you solved it 👍

**Comment by indapublic** [comment]
Sorry for up this old thread, but I receive same error.

```
 The geometry_type of a spatial column cannot be changed (Requested changing type from "POINT" to "GEOMETRY" for column "location" in table "objects"  
  )   
```

Code is old (about one year) and nothing changed for a long time

```
#[ORM\Column(name: "location", type: PostGISType::GEOMETRY, nullable: true, options: ['geometry_type' => 'POINT'])]
protected ?string $location = null;
```

**Comment by indapublic** [comment]
Field was declared in migration like:

```
location geometry(POINT, 0) DEFAULT NULL
```

**Comment by indapublic** [comment]
After column removing migration looks like:

```
ALTER TABLE objects ADD location geometry(GEOMETRY, 0) DEFAULT NULL
```

Is it expected or bug?

**Comment by letzpetz** [comment]
@indapublic I have the same error. No changes were made to the entity code. Did you find a solution to the problem?

> The geometry_type of a spatial column cannot be changed (Requested changing type from "POINT" to "GEOMETRY" for column "geom" in table "location")

> #[ORM\Column(name: "geom", type: "geometry", nullable: true, options: ["geometry_type" => "point", "srid" => 4326])]
    private ?string $geom;

**Comment by indapublic** [comment]
@letzpetz I was need to implement hotfix for this entity so I didn't have enough time to investigate, so I just renamed this column in database, executed `make:migration`,  changed generated migration by hands and returned old name for column in database, then executed new migration. I'll try to investigate it bit later when have some free time

**Comment by vtuz** [comment]
Same here. Needed to add extra field to the entity and migration isn't created because of such error. Few months ago there were no issues with it.

@indapublic - to add non-geometry column and create migration, I temporarily commented exception in DBALSchemaEventSubscriber.php, created, executed and turn all back. 

Hope to find what actually happened here.

**Comment by Miirek** [comment]
Same problem here. There must be change in way doctrine reading table metadata. @vtuz - hack worked, but not happy with it. Anyway thanks.

**Comment by nbitouze** [comment]
I had the same issue with version 2.1.0 of the package, updated to 2.4.0 and it fixed it for me.
