### ISSUE TITLE
Improvement proposal and Issue running unit tests

### ISSUE THREAD

**Issue by KaiGrassnick** [jsor/doctrine-postgis#65]
Hello

i'm currently trying to run the PHPUnit Tests locally and followed the instructions.

First thing i figured, the docs do not state, that you need to install composer dependencies and how its done.
Not an issue for me, but i would suggest, that his will be added to the HowTo Section on how to run the Tests ( in case you just start )

Second issue, the Scripts (run-xx-xx.sh) inject the volume via  `-v "$(PWD)":/app` i would suggest, that this should be changed to  `-v "${PWD}":/app`
While `$(PWD)` might work in some Environments `${PWD}` should work in more Environments

Now to the third and biggest issue: The Unit Tests do not run correctly on my machine.

Docker Compose for the Databases is running and i tried all the different versions. All result in the same errors

`PDOException: SQLSTATE[22023]: Invalid parameter value: 7 ERROR:  Geometry has Z dimension but column does not`

this happens in pretty much every UnitTest but here is an Example:

I get the following Error: 
```
/app/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28
/app/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:123
/app/vendor/doctrine/dbal/src/Statement.php:190
/app/vendor/doctrine/dbal/src/Statement.php:249
/app/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:280
/app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1179
/app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:443
/app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:403
/app/tests/Functions/GeographyTest.php:47

Caused by
PDOException: SQLSTATE[22023]: Invalid parameter value: 7 ERROR:  Geometry has Z dimension but column does not
```

Does anyone have a clue what i'm doing wrong and how to fix it?

Environment:
Windows 10 + WSL 2 + Docker Desktop with WSL 2 Integration. Setup for Linux Containers

**Comment by jsor** [comment]
The issues should all be fixed in  [v2.3.0](https://github.com/jsor/doctrine-postgis/releases/tag/v2.3.0).
