### ISSUE TITLE
Dql query using PostGIS functions

### ISSUE THREAD

**Issue by maxthev** [jsor/doctrine-postgis#7]
Hi ! it's me again :)

i'm stuck on how to use your PostGIS functions with Dql.

this is my code :

```
public function findTByGeo($lat, $lng, $distance = 30000) {
        $configuration = new \Doctrine\ORM\Configuration();
        $configuration->addCustomStringFunction('ST_Distance', 'Jsor\Doctrine\PostGIS\Functions\ST_Distance');
        $configuration->addCustomStringFunction('ST_GeographyFromText', 'Jsor\Doctrine\PostGIS\Functions\ST_GeographyFromText');

        $em = $this->getEntityManager();
        $dql = "SELECT t, ST_Distance(ST_GeographyFromText(SRID=4326;POINT(:lat :lng)), p.coordinates ) AS distance "
                . "FROM SiteBundle:Trainings t "
                . "JOIN t.place p "
                . "WHERE ST_Distance(ST_GeographyFromText(SRID=4326;POINT(:lat2 :lng2)), p.coordinates ) < :dist ";
        $requete = $em->createQuery($dql)
                ->setParameter(":lat", $lat)
                ->setParameter(":lng", $lng)
                ->setParameter(":lat2", $lat)
                ->setParameter(":lng2", $lng)
                ->setParameter(":dist", $distance);

        return $requete->getResult();
    }
```

i get this error now :

```
[Syntax Error] line 0, col 47: Error: Expected Doctrine\ORM\Query\Lexer::T_CLOSE_PARENTHESIS, got '='
500 Internal Server Error - QueryException
1 linked Exception: QueryException »
```

I don't understand why it doesn't work, am i doing something wrong ?

PS : 
i got to declare your functions in config.yml like this

```
        dql:
            string_functions:
                st_distance: Jsor\Doctrine\PostGIS\Functions\ST_Distance
                st_geographyfromtext: Jsor\Doctrine\PostGIS\Functions\ST_GeographyFromText
```

since this:

```
$configuration = new \Doctrine\ORM\Configuration();
        $configuration->addCustomStringFunction('ST_Distance', 'Jsor\Doctrine\PostGIS\Functions\ST_Distance');
        $configuration->addCustomStringFunction('ST_GeographyFromText', 'Jsor\Doctrine\PostGIS\Functions\ST_GeographyFromText');
```

does not seems to work.

Thanks a lot if you can help me again =)

**Comment by jsor** [comment]
`ST_GeographyFromText` expects a string like `ST_GeographyFromText('SRID=4326;POINT(1 2)')` (note the ' around the string).

If you need to use placeholders, you have to use

```
ST_Distance(ST_SetSRID(ST_Point(:lng, :lat), 4326), p.coordinates) AS distance
```

Also note, that the coordinate order of a POINT is longitude, latitude! See http://postgis.org/docs/ST_Point.html.

As for the configuration, registering the functions in the config.yml is the correct way. Using the `Configuration` is only needed if you setup the EntityManager by hand like [this](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/advanced-configuration.html).

**Comment by maxthev** [comment]
Thank you so much !

You solved my issue showing me how to deal with placeholder !

for the coordinate  order of a POINT ....... nice remark ! XD i just imagine how wrong were my results before you said that ...i won't forgot this now  ! 

can be closed ! thanks again :)

**Comment by jsor** [comment]
Glad it helped. Btw, i updated the [DQL functions section](https://github.com/jsor/doctrine-postgis#dql-functions) in the Readme, thanks for the hint.
