### ISSUE TITLE
Problem column geometry

### ISSUE THREAD

**Issue by Xeyos88** [jsor/doctrine-postgis#8]
I have a problem with the column geometry is created.

In a table postigs type geometry, normally you can load both POINT  both POLYGON, 2D and 3D.

In the column geometry created by the bundle you can only load or POINT or POLYGON. How may?

**Comment by jsor** [comment]
Can you give a little bit more information? How does your mapping look like and what data are you inserting into the table?

**Comment by Xeyos88** [comment]
Mapping 
 /**
     \* @ORM\Column(type="geometry")
     */
private $boundingBox;

And i try to insert:
e.g:
POINT(10 5 0) OR POLYGON((10 5 0, 10 10 0, 5 10 0, 5 5 0, 10 5 0)
Usually when you create a column of type geometry you can be inserted both points and polygons.

**Comment by jsor** [comment]
If you want to store 3D geometries, the mapping must be:

```
/**
* @ORM\Column(type="geometry", options={"geometry_type"="GEOMETRYZ"})
*/
private $boundingBox;
```

**Comment by jsor** [comment]
Closing for now, feel free to reopen if needed.
