### ISSUE TITLE
Call to a member function listSpatialIndexes() on null

### ISSUE THREAD

**Issue by mcnijman** [jsor/doctrine-postgis#9]
Hi,

I get the following error message:

PHP Fatal error:  Call to a member function listSpatialIndexes() on null in /var/www/xxx/vendor/jsor/doctrine-postgis/src/Event/DBALSchemaEventSubscriber.php on line 318

It looks like schemaManager is null. I am using zf2 with doctrine 2. Just enabled your module by registering the event subscriber. Any ideas?

Thanks

**Comment by jsor** [comment]
Looks like you're registering the event subscriber too late (after the first connection to the database). Can you show me your setup? I'm not very familiar with ZF2, but i posted a configuration example here: https://github.com/jsor/doctrine-postgis/issues/2#issuecomment-107206150

**Comment by mcnijman** [comment]
Thanks for your fast response!
The config sample from the other issue solved the problem. I used the bootstrap file for registering the event listener, which apparently is too late.
